/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegacyIndexRouteImport } from './routes/legacy/index'
import { Route as LegacyTermsOfServiceRouteImport } from './routes/legacy/terms-of-service'
import { Route as LegacyTeamRouteImport } from './routes/legacy/team'
import { Route as LegacyResearchRouteImport } from './routes/legacy/research'
import { Route as LegacyPublicationsRouteImport } from './routes/legacy/publications'
import { Route as LegacyPrivacyPolicyRouteImport } from './routes/legacy/privacy-policy'
import { Route as LegacyNewsRouteImport } from './routes/legacy/news'
import { Route as LegacyConsultingRouteImport } from './routes/legacy/consulting'
import { Route as LegacyChaptersRouteImport } from './routes/legacy/chapters'
import { Route as LegacyChallengeRouteImport } from './routes/legacy/challenge'
import { Route as LegacyArticlesRouteImport } from './routes/legacy/articles'
import { Route as LegacyAboutRouteImport } from './routes/legacy/about'
import { Route as LegacyNewsArticleIdRouteImport } from './routes/legacy/news.$articleId'
import { Route as LegacyCountriesCountryRouteImport } from './routes/legacy/countries.$country'

const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyTermsOfServiceRoute = LegacyTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyTeamRoute = LegacyTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyResearchRoute = LegacyResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyPublicationsRoute = LegacyPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyPrivacyPolicyRoute = LegacyPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyNewsRoute = LegacyNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyConsultingRoute = LegacyConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyChaptersRoute = LegacyChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyChallengeRoute = LegacyChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyArticlesRoute = LegacyArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyAboutRoute = LegacyAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyNewsArticleIdRoute = LegacyNewsArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => LegacyNewsRoute,
} as any)
const LegacyCountriesCountryRoute = LegacyCountriesCountryRouteImport.update({
  id: '/countries/$country',
  path: '/countries/$country',
  getParentRoute: () => LegacyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legacy': typeof LegacyRouteWithChildren
  '/legacy/about': typeof LegacyAboutRoute
  '/legacy/articles': typeof LegacyArticlesRoute
  '/legacy/challenge': typeof LegacyChallengeRoute
  '/legacy/chapters': typeof LegacyChaptersRoute
  '/legacy/consulting': typeof LegacyConsultingRoute
  '/legacy/news': typeof LegacyNewsRouteWithChildren
  '/legacy/privacy-policy': typeof LegacyPrivacyPolicyRoute
  '/legacy/publications': typeof LegacyPublicationsRoute
  '/legacy/research': typeof LegacyResearchRoute
  '/legacy/team': typeof LegacyTeamRoute
  '/legacy/terms-of-service': typeof LegacyTermsOfServiceRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/countries/$country': typeof LegacyCountriesCountryRoute
  '/legacy/news/$articleId': typeof LegacyNewsArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legacy/about': typeof LegacyAboutRoute
  '/legacy/articles': typeof LegacyArticlesRoute
  '/legacy/challenge': typeof LegacyChallengeRoute
  '/legacy/chapters': typeof LegacyChaptersRoute
  '/legacy/consulting': typeof LegacyConsultingRoute
  '/legacy/news': typeof LegacyNewsRouteWithChildren
  '/legacy/privacy-policy': typeof LegacyPrivacyPolicyRoute
  '/legacy/publications': typeof LegacyPublicationsRoute
  '/legacy/research': typeof LegacyResearchRoute
  '/legacy/team': typeof LegacyTeamRoute
  '/legacy/terms-of-service': typeof LegacyTermsOfServiceRoute
  '/legacy': typeof LegacyIndexRoute
  '/legacy/countries/$country': typeof LegacyCountriesCountryRoute
  '/legacy/news/$articleId': typeof LegacyNewsArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legacy': typeof LegacyRouteWithChildren
  '/legacy/about': typeof LegacyAboutRoute
  '/legacy/articles': typeof LegacyArticlesRoute
  '/legacy/challenge': typeof LegacyChallengeRoute
  '/legacy/chapters': typeof LegacyChaptersRoute
  '/legacy/consulting': typeof LegacyConsultingRoute
  '/legacy/news': typeof LegacyNewsRouteWithChildren
  '/legacy/privacy-policy': typeof LegacyPrivacyPolicyRoute
  '/legacy/publications': typeof LegacyPublicationsRoute
  '/legacy/research': typeof LegacyResearchRoute
  '/legacy/team': typeof LegacyTeamRoute
  '/legacy/terms-of-service': typeof LegacyTermsOfServiceRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/countries/$country': typeof LegacyCountriesCountryRoute
  '/legacy/news/$articleId': typeof LegacyNewsArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legacy'
    | '/legacy/about'
    | '/legacy/articles'
    | '/legacy/challenge'
    | '/legacy/chapters'
    | '/legacy/consulting'
    | '/legacy/news'
    | '/legacy/privacy-policy'
    | '/legacy/publications'
    | '/legacy/research'
    | '/legacy/team'
    | '/legacy/terms-of-service'
    | '/legacy/'
    | '/legacy/countries/$country'
    | '/legacy/news/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legacy/about'
    | '/legacy/articles'
    | '/legacy/challenge'
    | '/legacy/chapters'
    | '/legacy/consulting'
    | '/legacy/news'
    | '/legacy/privacy-policy'
    | '/legacy/publications'
    | '/legacy/research'
    | '/legacy/team'
    | '/legacy/terms-of-service'
    | '/legacy'
    | '/legacy/countries/$country'
    | '/legacy/news/$articleId'
  id:
    | '__root__'
    | '/'
    | '/legacy'
    | '/legacy/about'
    | '/legacy/articles'
    | '/legacy/challenge'
    | '/legacy/chapters'
    | '/legacy/consulting'
    | '/legacy/news'
    | '/legacy/privacy-policy'
    | '/legacy/publications'
    | '/legacy/research'
    | '/legacy/team'
    | '/legacy/terms-of-service'
    | '/legacy/'
    | '/legacy/countries/$country'
    | '/legacy/news/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegacyRoute: typeof LegacyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/': {
      id: '/legacy/'
      path: '/'
      fullPath: '/legacy/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/terms-of-service': {
      id: '/legacy/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/legacy/terms-of-service'
      preLoaderRoute: typeof LegacyTermsOfServiceRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/team': {
      id: '/legacy/team'
      path: '/team'
      fullPath: '/legacy/team'
      preLoaderRoute: typeof LegacyTeamRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/research': {
      id: '/legacy/research'
      path: '/research'
      fullPath: '/legacy/research'
      preLoaderRoute: typeof LegacyResearchRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/publications': {
      id: '/legacy/publications'
      path: '/publications'
      fullPath: '/legacy/publications'
      preLoaderRoute: typeof LegacyPublicationsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/privacy-policy': {
      id: '/legacy/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/legacy/privacy-policy'
      preLoaderRoute: typeof LegacyPrivacyPolicyRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/news': {
      id: '/legacy/news'
      path: '/news'
      fullPath: '/legacy/news'
      preLoaderRoute: typeof LegacyNewsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/consulting': {
      id: '/legacy/consulting'
      path: '/consulting'
      fullPath: '/legacy/consulting'
      preLoaderRoute: typeof LegacyConsultingRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/chapters': {
      id: '/legacy/chapters'
      path: '/chapters'
      fullPath: '/legacy/chapters'
      preLoaderRoute: typeof LegacyChaptersRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/challenge': {
      id: '/legacy/challenge'
      path: '/challenge'
      fullPath: '/legacy/challenge'
      preLoaderRoute: typeof LegacyChallengeRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/articles': {
      id: '/legacy/articles'
      path: '/articles'
      fullPath: '/legacy/articles'
      preLoaderRoute: typeof LegacyArticlesRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/about': {
      id: '/legacy/about'
      path: '/about'
      fullPath: '/legacy/about'
      preLoaderRoute: typeof LegacyAboutRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/news/$articleId': {
      id: '/legacy/news/$articleId'
      path: '/$articleId'
      fullPath: '/legacy/news/$articleId'
      preLoaderRoute: typeof LegacyNewsArticleIdRouteImport
      parentRoute: typeof LegacyNewsRoute
    }
    '/legacy/countries/$country': {
      id: '/legacy/countries/$country'
      path: '/countries/$country'
      fullPath: '/legacy/countries/$country'
      preLoaderRoute: typeof LegacyCountriesCountryRouteImport
      parentRoute: typeof LegacyRoute
    }
  }
}

interface LegacyNewsRouteChildren {
  LegacyNewsArticleIdRoute: typeof LegacyNewsArticleIdRoute
}

const LegacyNewsRouteChildren: LegacyNewsRouteChildren = {
  LegacyNewsArticleIdRoute: LegacyNewsArticleIdRoute,
}

const LegacyNewsRouteWithChildren = LegacyNewsRoute._addFileChildren(
  LegacyNewsRouteChildren,
)

interface LegacyRouteChildren {
  LegacyAboutRoute: typeof LegacyAboutRoute
  LegacyArticlesRoute: typeof LegacyArticlesRoute
  LegacyChallengeRoute: typeof LegacyChallengeRoute
  LegacyChaptersRoute: typeof LegacyChaptersRoute
  LegacyConsultingRoute: typeof LegacyConsultingRoute
  LegacyNewsRoute: typeof LegacyNewsRouteWithChildren
  LegacyPrivacyPolicyRoute: typeof LegacyPrivacyPolicyRoute
  LegacyPublicationsRoute: typeof LegacyPublicationsRoute
  LegacyResearchRoute: typeof LegacyResearchRoute
  LegacyTeamRoute: typeof LegacyTeamRoute
  LegacyTermsOfServiceRoute: typeof LegacyTermsOfServiceRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
  LegacyCountriesCountryRoute: typeof LegacyCountriesCountryRoute
}

const LegacyRouteChildren: LegacyRouteChildren = {
  LegacyAboutRoute: LegacyAboutRoute,
  LegacyArticlesRoute: LegacyArticlesRoute,
  LegacyChallengeRoute: LegacyChallengeRoute,
  LegacyChaptersRoute: LegacyChaptersRoute,
  LegacyConsultingRoute: LegacyConsultingRoute,
  LegacyNewsRoute: LegacyNewsRouteWithChildren,
  LegacyPrivacyPolicyRoute: LegacyPrivacyPolicyRoute,
  LegacyPublicationsRoute: LegacyPublicationsRoute,
  LegacyResearchRoute: LegacyResearchRoute,
  LegacyTeamRoute: LegacyTeamRoute,
  LegacyTermsOfServiceRoute: LegacyTermsOfServiceRoute,
  LegacyIndexRoute: LegacyIndexRoute,
  LegacyCountriesCountryRoute: LegacyCountriesCountryRoute,
}

const LegacyRouteWithChildren =
  LegacyRoute._addFileChildren(LegacyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegacyRoute: LegacyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
